version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local
  adminer:
    driver: local

services:
  ### Workspace Utilities ##################################
  workspace:
    build:
      context: ./docker/workspace
      args:
        - CHANGE_SOURCE=false
        - SHELL_OH_MY_ZSH=false
        - SHELL_OH_MY_ZSH_AUTOSUGESTIONS=false
        - SHELL_OH_MY_ZSH_ALIASES=false
        - BASE_IMAGE_TAG_PREFIX=latest
        - LARADOCK_PHP_VERSION=8.2
        - LARADOCK_PHALCON_VERSION=5.0.0
        - INSTALL_SUBVERSION=false
        - INSTALL_BZ2=false
        - INSTALL_GMP=false
        - INSTALL_GNUPG=false
        - INSTALL_XDEBUG=false
        - XDEBUG_PORT=9003
        - INSTALL_PCOV=true
        - INSTALL_PHPDBG=false
        - INSTALL_BLACKFIRE=false
        - INSTALL_SSH2=false
        - INSTALL_SOAP=false
        - INSTALL_XSL=false
        - INSTALL_LDAP=false
        - INSTALL_SMB=false
        - INSTALL_IMAP=false
        - INSTALL_MONGO=false
        - INSTALL_AMQP=false
        - INSTALL_CASSANDRA=false
        - INSTALL_ZMQ=false
        - INSTALL_GEARMAN=false
        - INSTALL_PHPREDIS=false
        - INSTALL_MSSQL=false
        - NVM_NODEJS_ORG_MIRROR=
        - INSTALL_NODE=false
        - NPM_REGISTRY=
        - NPM_FETCH_RETRIES=2
        - NPM_FETCH_RETRY_FACTOR=10
        - NPM_FETCH_RETRY_MINTIMEOUT=10000
        - NPM_FETCH_RETRY_MAXTIMEOUT=60000
        - INSTALL_PNPM=false
        - INSTALL_YARN=false
        - INSTALL_NPM_GULP=false
        - INSTALL_NPM_BOWER=false
        - INSTALL_NPM_VUE_CLI=false
        - INSTALL_NPM_ANGULAR_CLI=false
        - INSTALL_DRUSH=false
        - INSTALL_WP_CLI=false
        - INSTALL_DRUPAL_CONSOLE=false
        - INSTALL_AEROSPIKE=false
        - INSTALL_OCI8=false
        - INSTALL_V8JS=false
        - COMPOSER_GLOBAL_INSTALL=true
        - COMPOSER_VERSION=2
        - COMPOSER_AUTH_JSON=false
        - COMPOSER_REPO_PACKAGIST=
        - INSTALL_WORKSPACE_SSH=false
        - INSTALL_LARAVEL_ENVOY=false
        - INSTALL_LARAVEL_INSTALLER=false
        - INSTALL_XLSWRITER=false
        - INSTALL_DEPLOYER=false
        - INSTALL_PRESTISSIMO=false
        - INSTALL_LINUXBREW=false
        - INSTALL_MC=false
        - INSTALL_SYMFONY=false
        - INSTALL_PYTHON=false
        - INSTALL_PYTHON3=false
        - INSTALL_IMAGE_OPTIMIZERS=false
        - INSTALL_IMAGEMAGICK=false
        - INSTALL_TERRAFORM=false
        - INSTALL_DUSK_DEPS=false
        - INSTALL_PG_CLIENT=false
        - PG_CLIENT_VERSION=15
        - INSTALL_PHALCON=false
        - INSTALL_SWOOLE=false
        - INSTALL_TAINT=false
        - INSTALL_LIBPNG=false
        - INSTALL_GRAPHVIZ=false
        - INSTALL_IONCUBE=false
        - INSTALL_APCU=false
        - INSTALL_MYSQL_CLIENT=true
        - INSTALL_PING=false
        - INSTALL_SSHPASS=false
        - INSTALL_INOTIFY=false
        - INSTALL_FSWATCH=false
        - INSTALL_AST=true
        - INSTALL_YAML=false
        - INSTALL_RDKAFKA=false
        - INSTALL_MAILPARSE=false
        - INSTALL_GIT_PROMPT=false
        - INSTALL_XMLRPC=false
        - PUID=1000
        - PGID=1000
        - CHROME_DRIVER_VERSION=2.42
        - NODE_VERSION=lts/*
        - YARN_VERSION=latest
        - DRUSH_VERSION=8.4.6
        - AST_VERSION=1.0.10
        - IMAGEMAGICK_VERSION=latest
        - TZ=UTC
        - BLACKFIRE_CLIENT_ID="<client_id>"
        - BLACKFIRE_CLIENT_TOKEN="<client_token>"
        - INSTALL_POWERLINE=false
        - INSTALL_SUPERVISOR=false
        - INSTALL_FFMPEG=false
        - INSTALL_AUDIOWAVEFORM=false
        - INSTALL_WKHTMLTOPDF=false
        - WKHTMLTOPDF_VERSION=0.12.6-1
        - INSTALL_GNU_PARALLEL=false
        - INSTALL_LNAV=false
        - INSTALL_PROTOC=false
        - INSTALL_PHPDECIMAL=false
        - INSTALL_ZOOKEEPER=false
        - INSTALL_SSDB=false
        - INSTALL_TRADER=false
        - PROTOC_VERSION=latest
        - INSTALL_DOCKER_CLIENT=false
        - INSTALL_MEMCACHED=false
        - INSTALL_EVENT=false
        - INSTALL_DNSUTILS=true
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      ## APP_CODE_PATH_HOST:APP_CODE_PATH_CONTAINER APP_CODE_CONTAINER_FLAG
      - ./:/var/www:cached
    ports:
      ## WORKSPACE_SSH_PORT
      - "2222:22"
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=laradock
    networks:
      - frontend
      - backend
  ### MariaDB ##############################################
  mariadb:
    container_name: wordless-framework-mariadb
    build:
      context: ./docker/mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=lts
    volumes:
      - ~/.laradock/data/mariadb:/var/lib/mysql
      - ./docker/mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=default
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - backend
  ### Adminer ###########################################
  adminer:
    build:
      context: ./docker/adminer
      args:
        - INSTALL_MSSQL=false
    environment:
      - ADMINER_PLUGINS=
      - ADMINER_DESIGN=pepa-linha
      - ADMINER_DEFAULT_SERVER=mysql
    ports:
      - "8081:8080"
    networks:
      - frontend
      - backend
