version: '3.5'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mariadb:
    driver: local
  adminer:
    driver: local

services:
  ### Workspace Utilities ##################################
  workspace:
    build:
      context: ./docker/workspace
      args:
        - BASE_IMAGE_TAG_PREFIX=latest
        - LARADOCK_PHP_VERSION=8.2
        - INSTALL_XDEBUG=false
        - XDEBUG_PORT=9003
        - COMPOSER_GLOBAL_INSTALL=true
        - COMPOSER_VERSION=2
        - COMPOSER_AUTH_JSON=false
        - COMPOSER_REPO_PACKAGIST=
        - PUID=1000
        - PGID=1000
        - TZ=UTC
        - INSTALL_DNSUTILS=true
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      ## APP_CODE_PATH_HOST:APP_CODE_PATH_CONTAINER APP_CODE_CONTAINER_FLAG
      - ./:/var/www:cached
    extra_hosts:
      - "dockerhost:10.0.75.1"
    ports:
      ## WORKSPACE_SSH_PORT
      - "2222:22"
      ## WORKSPACE_BROWSERSYNC_HOST_PORT
      - "3000:3000"
      ## WORKSPACE_BROWSERSYNC_UI_HOST_PORT
      - "3001:3001"
      ## WORKSPACE_VUE_CLI_SERVE_HOST_PORT
      - "8080:8080"
      ## WORKSPACE_VUE_CLI_UI_HOST_PORT
      - "8001:8000"
      ## WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT
      - "4200:4200"
      ## WORKSPACE_VITE_PORT
      - "5173:5173"
    tty: true
    environment:
      - PHP_IDE_CONFIG=serverName=laradock
      - DOCKER_HOST=tcp://docker-in-docker:2376
      - DOCKER_TLS_VERIFY=1
      - DOCKER_TLS_CERTDIR=/certs
      - DOCKER_CERT_PATH=/certs/client
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend
      - backend
